### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by tonysy** [wuhuikai/FastFCN#2] opened 2019-03-30 02:42 UTC
Thanks for your work.
I have tried this script:
https://github.com/wuhuikai/FastFCN/blob/master/experiments/segmentation/scripts/encnet_res50_pcontext.sh 
with the hardware and software: 4xTitanXp, Ubuntu16.04, CUDA9.0, PyToch1.0

But I can't reproduce the performance reported in your paper.
I got pixAcc: 0.7747, mIoU: 0.4785 for single-scale,
and pixAcc: 0.7833, mIoU: 0.4898 for multi-scale.

I would appreciate your help. Thanks for your consideration.

**Comment by wuhuikai** [comment] 2019-03-30 09:04
In the same environment, I got 0.5105 for single-scale.
Can you provide your `scripts`, `running log` and `sha1sum of the model`?

**Comment by tonysy** [comment] 2019-04-01 01:41
The sha1sum of the model_best.pth.tar is: d581b28ac711fda74100529319d4853041ba0e2b  
I use the script in your project:
```
#train
CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py --dataset pcontext \
    --model encnet --jpu --aux --se-loss \
    --backbone resnet50 --checkname encnet_res50_pcontext

#test [single-scale]
CUDA_VISIBLE_DEVICES=0,1,2,3 python test.py --dataset pcontext \
    --model encnet --jpu --aux --se-loss \
    --backbone resnet50 --resume {MODEL} --split val --mode testval

#test [multi-scale]
CUDA_VISIBLE_DEVICES=0,1,2,3 python test.py --dataset pcontext \
    --model encnet --jpu --aux --se-loss \
    --backbone resnet50 --resume {MODEL} --split val --mode testval --ms
``` 
The script didn't store the log and I'am re-training it again for saving the logs.

Maybe you can provide a Dockerfile to make sure we can get the same performance for verification.

**Comment by tonysy** [comment] 2019-04-01 01:47
Another issue about the FPS measurement.
I have tried the `test_fps_params.py` for FPS measurement.
I use 
```
CUDA_VISIBLE_DEVICES=0 python test_fps_params.py --dataset pcontext \
    --model encnet --jpu --aux --se-loss \
    --backbone resnet50
```
get the following results:
![jpu_fps](https://user-images.githubusercontent.com/7881589/55298876-ba431f00-5462-11e9-8c6a-3c06513f497f.png)
which is similar to your reported FPS.
But when I remove the `--jpu` parameters in the same machine, I got:
![enc_fps](https://user-images.githubusercontent.com/7881589/55298890-cfb84900-5462-11e9-8baa-863182f4a3ed.png)
where the result is 78 FPS, different from the 18.77 FPS. I wonder is there anything wrong in my experiment? Or you use different repo to report the FPS of the original EncNet?

**Comment by wuhuikai** [comment] 2019-04-01 02:28
1. For the original EncNet, the script is `--model encnet --dilated --lateral`.
2. For the performance, can you first download the `pre-trained` model and verify its performence ?
3. I'll test the training script myself and tell you the result later.

**Comment by wuhuikai** [comment] 2019-04-01 09:02
@tonysy I realized that there's a bug in this version's code. This bug will be fixed soon.

**Closed as completed** 2019-04-01 09:11 UTC
Labels: bug

**Comment by wuhuikai** [comment] 2019-04-02 01:20
I got a mIoU `51.27%` with the updated code.
Here's the [log](https://drive.google.com/open?id=1M-4GUdlwUaSeQreA80wAS9VMTPWf3d0d) for training and evaluation.

**Comment by tonysy** [comment] 2019-04-17 00:56
Thanks for your update. While, I think the performance of EncNet reported in your work is not accurate, which is not fair for comparison. EncNet-Res50 is 51.0% and EncNet-Res101 is 54.1% reported by the author.
https://hangzhang.org/PyTorch-Encoding/experiments/segmentation.html

**Comment by wuhuikai** [comment] 2019-04-17 01:16
We cannot reproduce the performance reported in [https://hangzhang.org/PyTorch-Encoding/experiments/segmentation.html](https://hangzhang.org/PyTorch-Encoding/experiments/segmentation.html). The performance I report is reproduced with the official code.

**Comment by HolmesShuan** [comment] 2019-04-24 08:14
* @tonysy In [https://hangzhang.org/PyTorch-Encoding/experiments/segmentation.html#test-pre-trained-model](https://hangzhang.org/PyTorch-Encoding/experiments/segmentation.html#test-pre-trained-model)
> The test script is in the experiments/segmentation/ folder. For evaluating the model (**using MS**), for example Encnet_ResNet50_PContext:

**using MS** may explain the performance gap.

* @wuhuikai Could you please further release the code to reproduce the results of **Table 3**, i.e., mIoU measured on 60 classes w/ background. Thanks in advance.

**Comment by wuhuikai** [comment] 2019-04-24 08:28
@HolmesShuan For 60 classes, see [here](https://github.com/zhanghang1989/PyTorch-Encoding/issues/127#issuecomment-451353034).

**Comment by HolmesShuan** [comment] 2019-04-24 10:08
Table 1 results should be higher than Table 3, right? But 51.2 (Table 3) is higher than 51.05 (Table 1). Did I miss anything?

**Comment by wuhuikai** [comment] 2019-04-24 12:50
@HolmesShuan Table 3 is evaluated with `MS`.
